version: "2.3"
services:
    hironx_kinetic_ws:
        build: docker
        container_name: hironx_kinetic_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ./catkin_ws/src:/catkin_ws/src
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/kinetic/setup.bash && cd /catkin_ws && catkin build && bash"
